# Site settings
course_name: Courses of Faith
course_description: "A sampling of courses taught at Concordia Seminary for interested future seminarians, pastors and laity."


baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://sherixie.github.io/" # the base hostname & protocol for your site

schoolname: "Faith"
schoolurl: "https://faith.edu"
twitter_username: username 

address: |
    School of Witchcraft and Wizardry
    Hogwarts
    Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
